"helm":
  # Remote helm repo URL. UPDATE this as required.
  "repo": __HELM_REPO__
  "host": __REST_PORT__
  # Repo name referred within the xapp-manager
  "repo-name": __REPO_NAME__

  # helm username and password files
  "helm-username-file": "/opt/ric/secret/helm_repo_username"
  "helm-password-file": "/opt/ric/secret/helm_repo_password"
  "retry": 1
"xapp":
  #Namespace to install xAPPs
  "namespace": __XAPP_NAMESPACE__
  "tarDir": "/tmp"
  "schema": "descriptors/schema.json"
  "config": "config/config-file.json"
  "tmpConfig": "/tmp/config-file.json"
